import type { Metadata } from "next";
import { Inter, Modak } from "next/font/google";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import StoreModal from "@/components/modals/store-modal";
import  ModalProvider  from "@/providers/modal-provider";
import { Toasterprovider } from "@/providers/toast-provider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Toasterprovider/>
          <ModalProvider/>
          {children}</body>
      </html>
    </ClerkProvider>
  );
}
